/* groovylint-disable-next-line CompileStatic */
/* groovylint-disable CompileStatic */
pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                bat 'npm test'
            }
        }
        stage('Deploy') {
            steps {
            // Aquí puedes agregar pasos para desplegar tu aplicación, por ejemplo, enviarla a un servidor
            }
        }
    }
    post {
        success {
            echo 'El build ha sido exitoso. ¡Enhorabuena!'
        }
        failure {
            echo 'El build ha fallado. Por favor, revisa los errores.'
        }
    }
}
