/* groovylint-disable-next-line CompileStatic */
/* groovylint-disable CompileStatic */
pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                echo 'Installing'
            }
        }
        stage('Test') {
            steps {
                dir(Api_pruebas) {
                    sh 'npm test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Docker'
            }
        }
    // Otras etapas aquí...
    }
}
